theme: jekyll-theme-primer
title: BeatWatch℠ - The Ratings Authority of Drum & Bass Music
description: BeatWatch℠ is the ratings authority of Drum & Bass music. We help you find the best drum & bass music. We keep digging through the crates so you don't have to!
url: "https://beat.watch"
plugins:
  - jekyll-sitemap
google_analytics: UA-59188526-1
