theme: jekyll-theme-midnight
title: beat.watch - The Drum & Bass Music Ratings Authority
description: We help you find the best drum & bass music. We keep digging through the crates so you don't have to!
url: "https://beat.watch"
plugins:
  - jekyll-sitemap
google_analytics: UA-59188526-1
