# TEST - remote_theme: akiritsu/pRoJEct-NeGYa
theme: jekyll-theme-primer
# TEST - remote_theme: andrewbanchich/forty-jekyll-theme
title: Beat.Watch&#8480; - Qualitative Ratings for Drum & Bass Music
description: Beat.Watch&#8480; is a thorough qualitative ratings source for the Drum & Bass musical genre. We help you find the best drum & bass music by reviewing new releases on a monthly basis (so you don't have to)!
url: "https://beat.watch"
repo: selfserv/beatwatch
plugins:
  - jekyll-sitemap
google_analytics: UA-59188526-1
